services:

  nginx:
    build:
      context: ./srcs/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build:
      context: ./srcs/WordPress
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  mariadb:
    build:
      context: ./srcs/MariaDb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

networks:
  inception:

volumes:
  wordpress_data:
  mariadb_data:
  