services:
  nginx:
    build:
      context: ./srcs/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  wordpress:
    build:
      context: ./srcs/WordPress
    container_name: wordpress
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  mariadb:
    build:
      context: ./srcs/MariaDb
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

networks:
  inception:

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb

secrets:
  db_root_password:
    file: ${HOME}/.secrets/db_root_password.txt
  db_password:
    file: ${HOME}/.secrets/db_password.txt
  wp_admin_password:
    file: ${HOME}/.secrets/wp_admin_password.txt
  wp_user_password:
    file: ${HOME}/.secrets/wp_user_password.txt
